apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello
  namespace: fluxcd
spec:
  releaseName: hello-app
  chart:
    repository: ssh@github.com:gajadevops/flux-demo.git
    ref: master
    path: chart/hello
#     repository: https://stefanprodan.github.io/podinfo
#     version: 2.1.0
#     name: podinfo
  values:
    replicaCount: 1
