apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello
  namespace: flux
spec:
  releaseName: hello-app
  chart:
    git: git@github.com:Vishnu4226/Helm-flux-demo.git
    ref: master
    path: chart/hello
#     repository: https://stefanprodan.github.io/podinfo
#     version: 2.1.0
#     name: podinfo
  values:
    replicaCount: 1
